version: '3.4'

services:
  kafka1:
    image: confluentinc/cp-kafka:3.3.0
    hostname: kafka1
    networks:
      - zoo_net
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:19092
      KAFKA_LISTENERS: PLAINTEXT://kafka1:19092

  kafka2:
    image: confluentinc/cp-kafka:3.3.0
    hostname: kafka2
    networks:
      - zoo_net
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:19092
      KAFKA_LISTENERS: PLAINTEXT://kafka2:19092

  kafka3:
    image: confluentinc/cp-kafka:3.3.0
    hostname: kafka3
    networks:
      - zoo_net
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:19092
      KAFKA_LISTENERS: PLAINTEXT://kafka3:19092

  kafka4:
    image: confluentinc/cp-kafka:3.3.0
    hostname: kafka4
    networks:
      - zoo_net
    environment:
      KAFKA_BROKER_ID: 4
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka4:19092
      KAFKA_LISTENERS: PLAINTEXT://kafka4:19092

  kafka5:
    image: confluentinc/cp-kafka:3.3.0
    hostname: kafka5
    networks:
      - zoo_net
    environment:
      KAFKA_BROKER_ID: 5
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka5:19092
      KAFKA_LISTENERS: PLAINTEXT://kafka5:19092


networks:
  zoo_net:

